name: printing_demo
description: Pdf Printing Demo

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-224.0.dev <3.0.0'
  flutter: ">=1.26.0-17.1.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety
  open_file:
  path_provider:
  printing:
  url_launcher: ^6.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

dependency_overrides:
  pdf:
    path: ../pdf
  printing:
    path: ../printing

flutter:
  uses-material-design: true
  assets:
    - assets/
